version: '3'
services:
  piwigo:
    container_name: piwigo
    image: piwigo-docker
    networks:
      - piwigo-nw
    ports:
      - "8185:8000"

  mariadb:
    image: tobi312/rpi-mariadb:10.6-alpine
    container_name: piwidb
    env_file:
      - stack.env
    environment:
      - PUID=1000   ##change to your user id. 
      - PGID=1000   ##change to your user group ID. 
      #- MARIADB_ROOT_PASSWORD=xxxx
      - TZ=Europe/Berlin
      - MARIADB_DATABASE=piwigo
      - MARIADB_USER=piwigo
      #- MARIADB_PASSWORD=yyyy
    volumes:
      - /var/lib/docker/volumes/piwigo-db/_data:/config
    networks:
      - piwigo-nw
    ports:
      - 3308:3306
    restart: unless-stopped
    
networks:
  piwigo-nw:
